credentials:
  usernames:
    admin:
      email: admin@welleazy.com
      name: Admin User
      password: $2b$12$XVyndVDIyN.e4eerqNuLTeXDEYtVRkNb/9P3cLAqJWUuyBEDQMBdW  # Admin@321
    manager:
      email: manager@welleazy.com
      name: Manager User
      password: $2b$12$XLnZ9uKT.Yy5/3H9l6ZEGeBY7KseZVulG2Q8SN4YMK5l5ckIrsWF.  # Manage@321

cookie:
  expiry_days: 30
  key: welleazy_mis_auth_key_v9
  name: welleazy_auth_cookie_v9

preauthorized:
  emails: []
